ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdede2c3048>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa0479306d8>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffb184cdb00>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffb1825c400>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffb18271cc0>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6479691b00>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6478480cf8>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6478498c18>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f64796beba8>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6478482ac8>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd2992fd400>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd2980784e0>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd298019588>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd29802de48>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f08f52fcb70>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b533c68d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c109a8400>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585979bc88>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f58585b4b70>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f58585b4ac8>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f58585b2400>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5859799ba8>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f58597c0b70>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585855fac8>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5858565ac8>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f58585bd470>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585858ae10>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f58585be8d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f58597be748>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585979e668>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f58585c4438>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585979e860>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5858558668>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585855e7b8>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585858eb00>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f58585b20f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f58585b2dd8>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585858f4a8>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585855b588>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585855b2b0>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585855b710>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c485f98>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585855b898>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c489630>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585856c518>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c490b38>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c496cf8>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c499ac8>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585857eb38>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585857a828>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5858557080>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c4b7240>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c4b6278>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c480b70>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585979e7f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585858ae10>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c4bb1d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c486d68>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c4bb4a8>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c441390>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c4bd320>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c493da0>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c4a6da0>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c454400>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c443ac8>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c468208>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c48c9e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f585c4504a8>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc479b6a0>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR PROCESSING : http://localhost:80/GenbotCrawler/ : HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /GenbotCrawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc479bb70>: Failed to establish a new connection: [Errno 111] Connection refused',))
